### ISSUE TITLE
Error message when trying to run program

### ISSUE THREAD

**Issue by WTownsend23** [owenauch/NBA-Fantasy-Optimizer#1]
Traceback (most recent call last):
  File "/home/elwill/NBA-Fantasy-Optimizer-master/NBAFantasyStats.py", line 392, in <module>
    season_desc_df = get_desc_stats(season_df)
  File "/home/elwill/NBA-Fantasy-Optimizer-master/NBAFantasyStats.py", line 140, in get_desc_stats
    means = means.rename ("mean")
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 2264, in rename
    return super(Series, self).rename(index=index, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 606, in rename
    result._data = result._data.rename_axis(f, axis=baxis, copy=copy)
  File "/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 2588, in rename_axis
    obj.set_axis(axis, _transform_index(self.axes[axis], mapper))
  File "/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 4391, in _transform_index
    items = [func(x) for x in index]
TypeError: 'str' object is not callable

**Comment by owenauch** [comment]
Did you just run the algorithm in python like normal? It worked for me. Thanks for reporting it though!
